name: Publish Python Package

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build the package
      run: python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}  # PyPI username in GitHub Secrets
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}  # PyPI password in GitHub Secrets
      run: |
        python -m twine upload dist/*
