name: Publish Python Package

on:
  push:
    branches:
      - main  # This workflow runs on any push to the main branch

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Build the package
      run: python setup.py sdist bdist_wheel

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
